"""add email to silo candidates

Revision ID: 15dd4869fe04
Revises: 21ec6176d8fc
Create Date: 2026-08-13 20:40:20.886571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15dd4869fe04'
down_revision: Union[str, None] = '21ec6176d8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silo_candidates', sa.Column('email', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('silo_candidates', 'email')
    # ### end Alembic commands ###
