"""mca fields, activity ledger, enrichment, shadow scores, globe signals

Revision ID: 184d67a952e4
Revises: c72e38935204
Create Date: 2026-08-12 23:56:26.546820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '184d67a952e4'
down_revision: Union[str, None] = 'c72e38935204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres enum types don't pick up new members just because a new
    # table references the same type name -- ADD VALUE explicitly, or
    # inserting e.g. source='cobalt_intelligence' fails at runtime.
    # ADD VALUE can't run inside the same transaction as code that uses
    # the new value, but that's fine here: this migration only alters the
    # type and creates schema, no rows are inserted in this transaction.
    for new_value in (
        "cobalt_intelligence", "interzoid", "apollo", "openfda",
        "deepgram_nova", "highergov", "gfw_4wings", "gled",
    ):
        op.execute(f"ALTER TYPE telemetry_source ADD VALUE IF NOT EXISTS '{new_value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_uid', sa.UUID(), nullable=False),
    sa.Column('source', postgresql.ENUM('cme_globex', 'import_genius', 'seavantage', 'ucc_filings', 'sos_registries', 'regrid', 'drive_ocr', 'cobalt_intelligence', 'interzoid', 'apollo', 'openfda', 'deepgram_nova', 'highergov', 'gfw_4wings', 'gled', name='telemetry_source', create_type=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_results_entity_uid'), 'enrichment_results', ['entity_uid'], unique=False)
    op.create_table('globe_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', postgresql.ENUM('cme_globex', 'import_genius', 'seavantage', 'ucc_filings', 'sos_registries', 'regrid', 'drive_ocr', 'cobalt_intelligence', 'interzoid', 'apollo', 'openfda', 'deepgram_nova', 'highergov', 'gfw_4wings', 'gled', name='telemetry_source', create_type=False), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('intensity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entity_uid', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_globe_signals_entity_uid'), 'globe_signals', ['entity_uid'], unique=False)
    op.create_index(op.f('ix_globe_signals_observed_at'), 'globe_signals', ['observed_at'], unique=False)
    op.create_table('lead_activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_uid', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'note_change', 'follow_up_change', 'status_change', 'field_change', 'calendar_sync', 'click', 'enrichment', 'sheet_sync', name='activity_event_type'), nullable=False),
    sa.Column('source', sa.Enum('ui', 'api', 'webhook_sheet', 'system', name='activity_source'), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_uid'], ['master_log_entries.lead_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activity_events_lead_uid'), 'lead_activity_events', ['lead_uid'], unique=False)
    op.create_index(op.f('ix_lead_activity_events_occurred_at'), 'lead_activity_events', ['occurred_at'], unique=False)
    op.create_table('shadow_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_uid', sa.UUID(), nullable=False),
    sa.Column('predicted_funded_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.Enum('shadow', 'live', name='brain_mode'), nullable=False),
    sa.Column('training_set_size', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_uid'], ['master_log_entries.lead_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_scores_computed_at'), 'shadow_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_shadow_scores_lead_uid'), 'shadow_scores', ['lead_uid'], unique=False)
    op.add_column('master_log_entries', sa.Column('state', sa.String(length=64), nullable=True))
    op.add_column('master_log_entries', sa.Column('annual_revenue', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('master_log_entries', sa.Column('lender', sa.String(length=256), nullable=True))
    op.add_column('master_log_entries', sa.Column('payment_amt', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('master_log_entries', sa.Column('payment_freq', sa.String(length=64), nullable=True))
    op.add_column('master_log_entries', sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('master_log_entries', sa.Column('open_positions', sa.Integer(), nullable=True))
    op.add_column('master_log_entries', sa.Column('credit_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Note: the telemetry_source enum values added in upgrade() are not
    # removed here -- Postgres has no ALTER TYPE ... DROP VALUE. Harmless
    # to leave them (unused enum members don't affect existing rows).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_log_entries', 'credit_score')
    op.drop_column('master_log_entries', 'open_positions')
    op.drop_column('master_log_entries', 'current_balance')
    op.drop_column('master_log_entries', 'payment_freq')
    op.drop_column('master_log_entries', 'payment_amt')
    op.drop_column('master_log_entries', 'lender')
    op.drop_column('master_log_entries', 'annual_revenue')
    op.drop_column('master_log_entries', 'state')
    op.drop_index(op.f('ix_shadow_scores_lead_uid'), table_name='shadow_scores')
    op.drop_index(op.f('ix_shadow_scores_computed_at'), table_name='shadow_scores')
    op.drop_table('shadow_scores')
    op.drop_index(op.f('ix_lead_activity_events_occurred_at'), table_name='lead_activity_events')
    op.drop_index(op.f('ix_lead_activity_events_lead_uid'), table_name='lead_activity_events')
    op.drop_table('lead_activity_events')
    op.drop_index(op.f('ix_globe_signals_observed_at'), table_name='globe_signals')
    op.drop_index(op.f('ix_globe_signals_entity_uid'), table_name='globe_signals')
    op.drop_table('globe_signals')
    op.drop_index(op.f('ix_enrichment_results_entity_uid'), table_name='enrichment_results')
    op.drop_table('enrichment_results')
    # ### end Alembic commands ###
