"""add lat lon to silo candidates

Revision ID: 21ec6176d8fc
Revises: 55794ba6200d
Create Date: 2026-08-13 19:16:49.258897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21ec6176d8fc'
down_revision: Union[str, None] = '55794ba6200d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silo_candidates', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('silo_candidates', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('silo_candidates', 'longitude')
    op.drop_column('silo_candidates', 'latitude')
    # ### end Alembic commands ###
