"""add call_recordings table

Revision ID: 2fabbbfa103a
Revises: f3a9c1d8e2b4
Create Date: 2026-08-13 01:10:09.521155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2fabbbfa103a'
down_revision: Union[str, None] = 'f3a9c1d8e2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_uid', sa.UUID(), nullable=True),
    sa.Column('source_label', sa.String(length=512), nullable=False),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='call_analysis_status'), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('speakers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_uid'], ['master_log_entries.lead_uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_recordings_created_at'), 'call_recordings', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_recordings_lead_uid'), 'call_recordings', ['lead_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_recordings_lead_uid'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_created_at'), table_name='call_recordings')
    op.drop_table('call_recordings')
    # ### end Alembic commands ###
