"""add river surveillance tables

Revision ID: 55794ba6200d
Revises: b094eff02892
Create Date: 2026-08-13 17:22:47.153822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '55794ba6200d'
down_revision: Union[str, None] = 'b094eff02892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # telemetry_source already exists (created by an earlier migration) --
    # reuse it here with create_type=False instead of letting the
    # autogenerated sa.Enum(...) try to CREATE TYPE it a second time.
    telemetry_source_enum = postgresql.ENUM(
        'cme_globex', 'import_genius', 'seavantage', 'ucc_filings', 'sos_registries', 'regrid', 'drive_ocr',
        'cobalt_intelligence', 'interzoid', 'apollo', 'openfda', 'deepgram_nova', 'highergov', 'gfw_4wings',
        'gdelt', 'datalastic', 'vesselfinder', 'usace', name='telemetry_source', create_type=False,
    )

    op.create_table('geofence_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_name', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.Enum('zone_entry', 'zone_exit', 'velocity_anomaly', 'lock_queue_delay', 'lock_closure', name='geofence_event_type'), nullable=False),
    sa.Column('mmsi', sa.String(length=32), nullable=True),
    sa.Column('imo', sa.String(length=32), nullable=True),
    sa.Column('vessel_name', sa.String(length=256), nullable=True),
    sa.Column('speed_knots', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('stationary_minutes', sa.Integer(), nullable=True),
    sa.Column('entity_uid', sa.UUID(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=512), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofence_events_detected_at'), 'geofence_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_geofence_events_entity_uid'), 'geofence_events', ['entity_uid'], unique=False)
    op.create_index(op.f('ix_geofence_events_mmsi'), 'geofence_events', ['mmsi'], unique=False)
    op.create_index(op.f('ix_geofence_events_zone_name'), 'geofence_events', ['zone_name'], unique=False)
    op.create_table('waterway_friction_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_name', sa.String(length=256), nullable=False),
    sa.Column('friction_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('avg_lock_delay_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('active_queue_count', sa.Integer(), nullable=True),
    sa.Column('velocity_anomaly_count', sa.Integer(), nullable=True),
    sa.Column('baseline_transit_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waterway_friction_metrics_computed_at'), 'waterway_friction_metrics', ['computed_at'], unique=False)
    op.create_index(op.f('ix_waterway_friction_metrics_zone_name'), 'waterway_friction_metrics', ['zone_name'], unique=False)
    op.create_table('waterway_telemetry_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', telemetry_source_enum, nullable=False),
    sa.Column('zone_name', sa.String(length=256), nullable=False),
    sa.Column('mmsi', sa.String(length=32), nullable=True),
    sa.Column('imo', sa.String(length=32), nullable=True),
    sa.Column('vessel_name', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('speed_knots', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('draft_meters', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waterway_telemetry_snapshots_imo'), 'waterway_telemetry_snapshots', ['imo'], unique=False)
    op.create_index(op.f('ix_waterway_telemetry_snapshots_mmsi'), 'waterway_telemetry_snapshots', ['mmsi'], unique=False)
    op.create_index(op.f('ix_waterway_telemetry_snapshots_observed_at'), 'waterway_telemetry_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_waterway_telemetry_snapshots_zone_name'), 'waterway_telemetry_snapshots', ['zone_name'], unique=False)
    op.create_table('waterway_triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.Enum('distress_supply_starvation', 'expansion_throughput_spike', name='waterway_trigger_type'), nullable=False),
    sa.Column('entity_uid', sa.UUID(), nullable=True),
    sa.Column('company_name_guess', sa.String(length=256), nullable=True),
    sa.Column('zone_name', sa.String(length=256), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waterway_triggers_created_at'), 'waterway_triggers', ['created_at'], unique=False)
    op.create_index(op.f('ix_waterway_triggers_entity_uid'), 'waterway_triggers', ['entity_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waterway_triggers_entity_uid'), table_name='waterway_triggers')
    op.drop_index(op.f('ix_waterway_triggers_created_at'), table_name='waterway_triggers')
    op.drop_table('waterway_triggers')
    op.drop_index(op.f('ix_waterway_telemetry_snapshots_zone_name'), table_name='waterway_telemetry_snapshots')
    op.drop_index(op.f('ix_waterway_telemetry_snapshots_observed_at'), table_name='waterway_telemetry_snapshots')
    op.drop_index(op.f('ix_waterway_telemetry_snapshots_mmsi'), table_name='waterway_telemetry_snapshots')
    op.drop_index(op.f('ix_waterway_telemetry_snapshots_imo'), table_name='waterway_telemetry_snapshots')
    op.drop_table('waterway_telemetry_snapshots')
    op.drop_index(op.f('ix_waterway_friction_metrics_zone_name'), table_name='waterway_friction_metrics')
    op.drop_index(op.f('ix_waterway_friction_metrics_computed_at'), table_name='waterway_friction_metrics')
    op.drop_table('waterway_friction_metrics')
    op.drop_index(op.f('ix_geofence_events_zone_name'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_mmsi'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_entity_uid'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_detected_at'), table_name='geofence_events')
    op.drop_table('geofence_events')
    # ### end Alembic commands ###
