"""add pitch recording url to dialer campaigns

Revision ID: 86634ea52624
Revises: cfbf18831230
Create Date: 2026-08-13 22:30:39.516565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86634ea52624'
down_revision: Union[str, None] = 'cfbf18831230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialer_campaigns', sa.Column('pitch_recording_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialer_campaigns', 'pitch_recording_url')
    # ### end Alembic commands ###
