"""rework master log links, drop loan amount requested

Revision ID: c47451583649
Revises: 86634ea52624
Create Date: 2026-08-15 19:40:50.760499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c47451583649'
down_revision: Union[str, None] = '86634ea52624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_log_entries', sa.Column('financials_link', sa.String(length=1024), nullable=True))
    op.add_column('master_log_entries', sa.Column('transcripts_link', sa.String(length=1024), nullable=True))
    op.drop_column('master_log_entries', 'loan_amount_requested')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_log_entries', sa.Column('loan_amount_requested', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.drop_column('master_log_entries', 'transcripts_link')
    op.drop_column('master_log_entries', 'financials_link')
    # ### end Alembic commands ###
