"""initial schema

Revision ID: c72e38935204
Revises: 
Create Date: 2026-08-12 23:22:29.623096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'c72e38935204'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_log_entries',
    sa.Column('lead_uid', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=256), nullable=False),
    sa.Column('contact_name', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('co_broker', sa.Enum('Nick F', 'Mike F', 'Vinny', 'Victor', 'Gallo', 'Shaun', 'Kris', 'DanStol', 'Roman', 'James', 'Alfred', 'Marcus', 'Ricky', 'Zack', 'Emilio', 'Jorge', 'Tony', 'Seb', name='co_broker'), nullable=False),
    sa.Column('status', sa.Enum('New lead', 'App Sent', 'Docs Owed', 'Chase Docs', 'Docs in', 'In negotiation', 'Offer Made Not Sold', 'Sold Deal Killed', 'Deal Stalled Proxy Pass', 'Funded', 'Ghosted', 'Loss to Competitor', 'Dog Shit', name='master_log_status'), nullable=False),
    sa.Column('loan_amount_requested', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dossier_drive_link', sa.String(length=1024), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=256), nullable=True),
    sa.Column('extra_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('lead_uid')
    )
    op.create_table('telemetry_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('cme_globex', 'import_genius', 'seavantage', 'ucc_filings', 'sos_registries', 'regrid', 'drive_ocr', name='telemetry_source'), nullable=False),
    sa.Column('entity_uid', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_entity_uid'), 'telemetry_events', ['entity_uid'], unique=False)
    op.create_table('hazard_snapshots',
    sa.Column('lead_uid', sa.UUID(), nullable=False),
    sa.Column('survival_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('days_in_stage', sa.Integer(), nullable=False),
    sa.Column('next_stage_transition_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_uid'], ['master_log_entries.lead_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_uid')
    )
    op.create_table('silo_candidates',
    sa.Column('candidate_uid', sa.UUID(), nullable=False),
    sa.Column('silo', sa.Enum('CME Macro Funnel', 'Tariff Silo', 'Food Processing & Fabrication Silo', 'Oil & Gas / Refining Silo', 'Heavy Machinery & Industrial Equipment Silo', 'Agriculture & Grain Handling Silo', 'Healthcare & Pharma Silo', 'E-Commerce & Fulfillment Silo', 'HigherGov Funnel', name='silo_name'), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=False),
    sa.Column('contact_name', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('source_reference', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dossier_drive_link', sa.String(length=1024), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'converted', 'dismissed', name='silo_candidate_status'), nullable=False),
    sa.Column('converted_lead_uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_lead_uid'], ['master_log_entries.lead_uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('candidate_uid')
    )
    op.create_table('status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_uid', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('New lead', 'App Sent', 'Docs Owed', 'Chase Docs', 'Docs in', 'In negotiation', 'Offer Made Not Sold', 'Sold Deal Killed', 'Deal Stalled Proxy Pass', 'Funded', 'Ghosted', 'Loss to Competitor', 'Dog Shit', name='master_log_status'), nullable=True),
    sa.Column('to_status', sa.Enum('New lead', 'App Sent', 'Docs Owed', 'Chase Docs', 'Docs in', 'In negotiation', 'Offer Made Not Sold', 'Sold Deal Killed', 'Deal Stalled Proxy Pass', 'Funded', 'Ghosted', 'Loss to Competitor', 'Dog Shit', name='master_log_status'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_uid'], ['master_log_entries.lead_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history')
    op.drop_table('silo_candidates')
    op.drop_table('hazard_snapshots')
    op.drop_index(op.f('ix_telemetry_events_entity_uid'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_table('master_log_entries')
    # ### end Alembic commands ###
