"""add dialer signalwire tables

Revision ID: cfbf18831230
Revises: 15dd4869fe04
Create Date: 2026-08-13 21:22:49.400716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cfbf18831230'
down_revision: Union[str, None] = '15dd4869fe04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialer_number_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialer_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('campaign_type', sa.Enum('outbound', name='dialer_campaign_type'), nullable=False),
    sa.Column('number_pool_id', sa.UUID(), nullable=True),
    sa.Column('lead_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('caller_connect_number', sa.String(length=32), nullable=True),
    sa.Column('max_attempts_per_lead', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['number_pool_id'], ['dialer_number_pools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialer_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('area_code', sa.String(length=8), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('signalwire_number_sid', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['dialer_number_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_dialer_numbers_area_code'), 'dialer_numbers', ['area_code'], unique=False)
    op.create_table('dialer_call_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('lead_uid', sa.UUID(), nullable=True),
    sa.Column('silo_candidate_uid', sa.UUID(), nullable=True),
    sa.Column('from_number_id', sa.UUID(), nullable=True),
    sa.Column('to_number', sa.String(length=32), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('signalwire_call_sid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('queued', 'ringing', 'in-progress', 'completed', 'busy', 'no-answer', 'failed', 'canceled', name='dialer_call_status'), nullable=False),
    sa.Column('recording_url', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disposition', sa.Enum('unset', 'advance', 'purge', name='dialer_disposition'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['dialer_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_number_id'], ['dialer_numbers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_uid'], ['master_log_entries.lead_uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['silo_candidate_uid'], ['silo_candidates.candidate_uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialer_call_attempts_campaign_id'), 'dialer_call_attempts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_dialer_call_attempts_created_at'), 'dialer_call_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_dialer_call_attempts_lead_uid'), 'dialer_call_attempts', ['lead_uid'], unique=False)
    op.create_index(op.f('ix_dialer_call_attempts_signalwire_call_sid'), 'dialer_call_attempts', ['signalwire_call_sid'], unique=False)
    op.create_index(op.f('ix_dialer_call_attempts_silo_candidate_uid'), 'dialer_call_attempts', ['silo_candidate_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialer_call_attempts_silo_candidate_uid'), table_name='dialer_call_attempts')
    op.drop_index(op.f('ix_dialer_call_attempts_signalwire_call_sid'), table_name='dialer_call_attempts')
    op.drop_index(op.f('ix_dialer_call_attempts_lead_uid'), table_name='dialer_call_attempts')
    op.drop_index(op.f('ix_dialer_call_attempts_created_at'), table_name='dialer_call_attempts')
    op.drop_index(op.f('ix_dialer_call_attempts_campaign_id'), table_name='dialer_call_attempts')
    op.drop_table('dialer_call_attempts')
    op.drop_index(op.f('ix_dialer_numbers_area_code'), table_name='dialer_numbers')
    op.drop_table('dialer_numbers')
    op.drop_table('dialer_campaigns')
    op.drop_table('dialer_number_pools')
    # ### end Alembic commands ###
